AWSTemplateFormatVersion: "2010-09-09"
Description: DevOps Project - ALB + ASG Stack

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  PublicSubnets:
    Type: CommaDelimitedList

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

  LaunchTemplateId:
    Type: String

  LaunchTemplateVersion:
    Type: String

Resources:

  DevOpsALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: devops-alb
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets: !Ref PublicSubnets

  DevOpsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: devops-tg
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  DevOpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref DevOpsALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DevOpsTargetGroup

  DevOpsASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref PublicSubnets
      DesiredCapacity: 1
      MinSize: 1
      MaxSize: 2
      TargetGroupARNs:
        - !Ref DevOpsTargetGroup
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref LaunchTemplateVersion

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS Name
    Value: !GetAtt DevOpsALB.DNSName
